# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

#
# Created: 18th August 2025
# Updated: 27th August 2025
#

name: Go

on:
  push:
    branches: [ "master", "dev", "gha" ]
  pull_request:
    branches: [ "master", "dev", "gha" ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # go-version: [ '1.18', '1.19', '1.20', '1.21', '1.22', '1.23', '1.24' ]
        go-version: [ '1.20', '1.21', '1.22', '1.23', '1.24' ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Display Go version
      run: go version

    - name: Build
      run: ./build.sh

    - name: Test
      run: ./run_all_unit_tests.sh
